In [2]:
import pandas as pd 
from dotenv import load_dotenv
import duckdb

# 1. Connexion a motherduckdb
load_dotenv()
con = duckdb.connect("md:my_db")

In [12]:
df = con.execute("SELECT * EXCLUDE(date_importation), CAST(date_importation AS DATE) AS date_importation FROM clean_meteo;").df()

df

     date_meteo   temp_max   temp_min  precipitations date_importation
0    2020-06-20  21.200001  10.000000             0.3       2026-10-20
1    2020-06-21  22.600000  11.300000             0.0       2026-10-20
2    2020-06-22  23.500000  15.200000             0.0       2026-10-20
3    2020-06-23  26.100000  13.400000             0.0       2026-10-20
4    2020-06-24  27.799999  15.400000             0.0       2026-10-20
...         ...        ...        ...             ...              ...
2292 2026-09-29  24.600000  15.000000             0.0       2026-10-20
2293 2026-09-30  26.299999  16.799999             0.2       2026-10-20
2294 2026-10-01  19.200001  15.800000             9.5       2026-10-20
2295 2026-10-02  20.600000  14.300000             0.0       2026-10-20
2296 2026-10-03  22.299999  14.300000             0.2       2026-10-20

[2297 rows x 5 columns]

In [15]:
con.execute("SELECT * FROM raw_ventes;").df()

,Date,Site,Ca_ttc,Cb,Cb manuelle,Espece,Cheque,Bon cadeau,Virement,En compte,Taxes_20,Taxes_10,Taxes_5.5,Ca_ht,Nb_de_cvts,Food_ht,Bev_ht,date_importation,date_imp_date
0,2020-06-20,Guinguette,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,3 236,<NA>,NaN,NaN,2026-10-20 23:39:30.850138+02:00,2026-10-20
1,2020-06-21,Guinguette,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,2 489,<NA>,NaN,NaN,2026-10-20 23:39:30.850138+02:00,2026-10-20
2,2020-06-22,Guinguette,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1 155,<NA>,NaN,NaN,2026-10-20 23:39:30.850138+02:00,2026-10-20
3,2020-06-23,Guinguette,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1 719,<NA>,NaN,NaN,2026-10-20 23:39:30.850138+02:00,2026-10-20
4,2020-06-24,Guinguette,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,2 136,<NA>,NaN,NaN,2026-10-20 23:39:30.850138+02:00,2026-10-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1750,2026-09-23,Restaurant,1 984,1 984,NaN,NaN,NaN,NaN,NaN,NaN,577,1 407,<NA>,1 760,25,1 227,532,2026-10-20 23:39:30.850138+02:00,2026-10-20
1751,2026-09-24,Restaurant,1 008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,898,17,649,249,2026-10-20 23:39:30.850138+02:00,2026-10-20
1752,2026-09-26,Restaurant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,12 513,45,4 782,1 929,2026-10-20 23:39:30.850138+02:00,2026-10-20
1753,2026-10-01,Restaurant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,6 215,44,1 909,1 506,2026-10-20 23:39:30.850138+02:00,2026-10-20
1754,2026-10-03,Restaurant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,7 698,45,3 570,719,2026-10-20 23:39:30.850138+02:00,2026-10-20